kind: service
apiversion: v1
metadata:
  name: myservice
  label:
    app: myspringbootapp
spec:
  selector: myspringbootapp
    app:  myspringbootapp
    
type: LoadBalencer
ports: 
  
  - nodePort: 30036
  port: 80
  targetport: 9099
